# Generated by Django 5.1.7 on 2025-03-23 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('os_project', '0001_initial'),
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='os_project.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sponsored_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='user_profile.womenintech'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.payment'),
        ),
        migrations.AddField(
            model_name='projectfunding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_project.project'),
        ),
        migrations.AddField(
            model_name='witfunding',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.payment'),
        ),
        migrations.AddField(
            model_name='witfunding',
            name='wit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.womenintech'),
        ),
    ]
