# Generated by Django 5.1.7 on 2025-03-22 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('os_project', '0003_migrate_user_data'),
        ('user_profile', '0004_remove_os_maintainer_favourite_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='os_project.project'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sponsored_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='user_profile.womenintech'),
        ),
    ]
