# Generated by Django 5.1.7 on 2025-03-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_payment_country_projectfunding_witfunding'),
        ('donations', '0002_payment_project_payment_sponsored_user'),
    ]

    operations = [
    ]
