# Generated by Django 5.1.7 on 2025-03-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("os_project", "0003_migrate_user_data"),
        ("user_profile", "0003_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="favourite_projects",
            field=models.ManyToManyField(blank=True, to="os_project.project"),
        ),
    ]
