# Generated by Django 5.1.7 on 2025-03-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_project', '0003_migrate_user_data'),
        ('user_profile', '0003_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os_maintainer',
            name='favourite_projects',
        ),
        migrations.AlterUniqueTogether(
            name='favouriteprojectwit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favouriteprojectwit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='favouriteprojectwit',
            name='wit',
        ),
        migrations.RemoveField(
            model_name='womenintech',
            name='favourite_projects',
        ),
        migrations.CreateModel(
            name='FavouriteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_project.project')),
            ],
            options={
                'unique_together': {('profile', 'project')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_projects',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', through='user_profile.FavouriteProject', to='os_project.project'),
        ),
        migrations.DeleteModel(
            name='FavouriteProjectOS',
        ),
        migrations.DeleteModel(
            name='FavouriteProjectWIT',
        ),
    ]
