# Generated by Django 5.1.7 on 2025-03-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_project', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_wit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='user_profile.womenintech'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='user_profile.os_maintainer'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='os_project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='os_project.projectcategory'),
        ),
        migrations.AddField(
            model_name='projectinterest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='os_project.project'),
        ),
        migrations.AddField(
            model_name='projectinterest',
            name='wit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_interests', to='user_profile.womenintech'),
        ),
        migrations.AddField(
            model_name='projectmentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_projects', to='user_profile.mentor'),
        ),
        migrations.AddField(
            model_name='projectmentor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='os_project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='os_project.projecttag'),
        ),
        migrations.AlterUniqueTogether(
            name='projectinterest',
            unique_together={('project', 'wit')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmentor',
            unique_together={('project', 'mentor')},
        ),
    ]
